apiVersion: v1
kind: ServiceAccount
metadata:
  name: logiaccounting-api
  namespace: logiaccounting
  labels:
    app: logiaccounting-pro

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: logiaccounting-api-role
  namespace: logiaccounting
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: logiaccounting-api-binding
  namespace: logiaccounting
subjects:
  - kind: ServiceAccount
    name: logiaccounting-api
    namespace: logiaccounting
roleRef:
  kind: Role
  name: logiaccounting-api-role
  apiGroup: rbac.authorization.k8s.io
